Search.appendIndex(
    [
                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository",
            "name": "FolderRepository",
            "summary": "A\u0020repository\u0020for\u0020Folders",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AgetWorkspace\u0028\u0029",
            "name": "getWorkspace",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_getWorkspace"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AinitializeObject\u0028\u0029",
            "name": "initializeObject",
            "summary": "Executed\u0020by\u0020Flow\u0020Object\u0020Framework",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_initializeObject"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AaddFolder\u0028\u0029",
            "name": "addFolder",
            "summary": "Add\u0020a\u0020folder\u0020to\u0020the\u0020folder\u0020system",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_addFolder"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AgetNodeTypeByName\u0028\u0029",
            "name": "getNodeTypeByName",
            "summary": "Get\u0020NodeType\u0020by\u0020node\u0020type\u0020name.\u0020Fallback\u0020is\u0020configuration\u0020\u0060Neos.Folder.defaults.nodeType\u0060\u0020\u0028standard\nconfiguration\u0020is\u0020\u0060Neos.Folder\u003AFolder\u0060\u0029.\u0020Checks\u0020if\u0020NodeType\u0020of\u0020type\u0020nodeTypeName\u0020has\u0020the\u0020demanded\ndefault\u0020properties.",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_getNodeTypeByName"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A_uniqueNodeName\u0028\u0029",
            "name": "_uniqueNodeName",
            "summary": "Get\u0020unique\u0020node\u0020name\u0020from\u0020\u0024title",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method__uniqueNodeName"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003Apersist\u0028\u0029",
            "name": "persist",
            "summary": "flush\u0020and\u0020persist",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_persist"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A_titlePath\u0028\u0029",
            "name": "_titlePath",
            "summary": "Make\u0020titlePath\u0020for\u0020\u0024folderNode",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method__titlePath"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AsetTitleAndTitlePath\u0028\u0029",
            "name": "setTitleAndTitlePath",
            "summary": "Set\u0020title\u0020and\u0020titlePath\u0020at\u0020folder",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_setTitleAndTitlePath"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A_setTitleAndTitlePath\u0028\u0029",
            "name": "_setTitleAndTitlePath",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method__setTitleAndTitlePath"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AgetFolderTree\u0028\u0029",
            "name": "getFolderTree",
            "summary": "Collect\u0020all\u0020folder\u0020entries\u0020matching\u0020to\u0020\u0024bases\u0020\u0028default\u003A\u0020all\u0029",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_getFolderTree"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A_buildFolderTree\u0028\u0029",
            "name": "_buildFolderTree",
            "summary": "Get\u0020folder\u0020information\u003A",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method__buildFolderTree"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AremoveFolder\u0028\u0029",
            "name": "removeFolder",
            "summary": "Remove\u0020a\u0020folder",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_removeFolder"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A_remove\u0028\u0029",
            "name": "_remove",
            "summary": "Perform\u0020the\u0020removal\u0020of\u0020a\u0020folder",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method__remove"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AmoveFolder\u0028\u0029",
            "name": "moveFolder",
            "summary": "Move\u0020a\u0020folder",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_moveFolder"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AsetProperties\u0028\u0029",
            "name": "setProperties",
            "summary": "Set\u0020or\u0020clear\u0020properties\u0020at\u0020a\u0020folder",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_setProperties"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A_validProperties\u0028\u0029",
            "name": "_validProperties",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method__validProperties"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AclearAllProperties\u0028\u0029",
            "name": "clearAllProperties",
            "summary": "Clear\u0020properties\u0020at\u0020folder",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_clearAllProperties"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003Aassociate\u0028\u0029",
            "name": "associate",
            "summary": "Set\u0020or\u0020clear\u0020association",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#method_associate"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003ANAME_KEY",
            "name": "NAME_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_NAME_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AIDENTIFIER_KEY",
            "name": "IDENTIFIER_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_IDENTIFIER_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003APATH_KEY",
            "name": "PATH_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_PATH_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003ATITLE_PATH_KEY",
            "name": "TITLE_PATH_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_TITLE_PATH_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003ANODE_TYPE_KEY",
            "name": "NODE_TYPE_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_NODE_TYPE_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AINDEX_KEY",
            "name": "INDEX_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_INDEX_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AVARIANTS_KEY",
            "name": "VARIANTS_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_VARIANTS_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003ATITLE_KEY",
            "name": "TITLE_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_TITLE_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003ADIMENSIONS_KEY",
            "name": "DIMENSIONS_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_DIMENSIONS_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003APROPERTY_KEY",
            "name": "PROPERTY_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_PROPERTY_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003AASSOCIATIONS_KEY",
            "name": "ASSOCIATIONS_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_ASSOCIATIONS_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003ACHILDREN_KEY",
            "name": "CHILDREN_KEY",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_CHILDREN_KEY"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003ADEFAULT_PROPERTIES",
            "name": "DEFAULT_PROPERTIES",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#constant_DEFAULT_PROPERTIES"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A\u0024titlePropertyKey",
            "name": "titlePropertyKey",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#property_titlePropertyKey"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A\u0024titlePathPropertyKey",
            "name": "titlePathPropertyKey",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#property_titlePathPropertyKey"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A\u0024associationsPropertyKey",
            "name": "associationsPropertyKey",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#property_associationsPropertyKey"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A\u0024defaultNodeTypeName",
            "name": "defaultNodeTypeName",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#property_defaultNodeTypeName"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A\u0024contextFactory",
            "name": "contextFactory",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#property_contextFactory"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A\u0024context",
            "name": "context",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#property_context"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository\\FolderRepository\u003A\u003A\u0024workspace",
            "name": "workspace",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Repository-FolderRepository.html#property_workspace"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\Diacritics",
            "name": "Diacritics",
            "summary": "Diacritics\u0020\u0028umlaut\u0029\u0020and\u0020greek\u0020character\u0020conversion\u0020to\u0020ascii,\u0020diacritics\u0020strlen\u0020etc.",
            "url": "classes/Neos-Folder-Domain-Service-Diacritics.html"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\Diacritics\u003A\u003AtoAscii\u0028\u0029",
            "name": "toAscii",
            "summary": "Convert\u0020diacritics\u0020input\u0020\u0020to\u0020ascii",
            "url": "classes/Neos-Folder-Domain-Service-Diacritics.html#method_toAscii"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\Diacritics\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "Convert\u0020diacritics\u0020to\u0020lower\u0020case\u0020ascii\u0020and\u0020non\u0020\u0022word\u0022\u0020characters\u0020\u0028except\u0020slash\u0029\u0020to\u0020dash",
            "url": "classes/Neos-Folder-Domain-Service-Diacritics.html#method_path"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\Diacritics\u003A\u003Astrlen\u0028\u0029",
            "name": "strlen",
            "summary": "strlen\u0020with\u0020respect\u0020to\u0020diacritics",
            "url": "classes/Neos-Folder-Domain-Service-Diacritics.html#method_strlen"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\Diacritics\u003A\u003Astr_pad\u0028\u0029",
            "name": "str_pad",
            "summary": "str_pad\u0020with\u0020respect\u0020to\u0020diacritics",
            "url": "classes/Neos-Folder-Domain-Service-Diacritics.html#method_str_pad"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\Diacritics\u003A\u003AUPPER_CASE",
            "name": "UPPER_CASE",
            "summary": "Upper\u0020case\u0020\u005B\u0020diacritics,\u0020ascii\u0020\u005D",
            "url": "classes/Neos-Folder-Domain-Service-Diacritics.html#constant_UPPER_CASE"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\Diacritics\u003A\u003ALOWER_CASE",
            "name": "LOWER_CASE",
            "summary": "Lower\u0020case\u0020\u005B\u0020diacritics,\u0020ascii\u0020\u005D",
            "url": "classes/Neos-Folder-Domain-Service-Diacritics.html#constant_LOWER_CASE"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\FolderContext",
            "name": "FolderContext",
            "summary": "Context\u0020for\u0020Neos\u0020Folders",
            "url": "classes/Neos-Folder-Domain-Service-FolderContext.html"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\FolderContext\u003A\u003AverifyAndConvertDimensions\u0028\u0029",
            "name": "verifyAndConvertDimensions",
            "summary": "Convert\u0020json\u0020dimension\u0020string\u0020to\u0020dimension\u0020array\u0020and\u0020compared\u0020to\u0020\u0024this\u002D\u003EsubGraphDimensions",
            "url": "classes/Neos-Folder-Domain-Service-FolderContext.html#method_verifyAndConvertDimensions"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\FolderContext\u003A\u003AgetDefaultDimensions\u0028\u0029",
            "name": "getDefaultDimensions",
            "summary": "Get\u0020default\u0020dimensions",
            "url": "classes/Neos-Folder-Domain-Service-FolderContext.html#method_getDefaultDimensions"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\FolderContext\u003A\u003AadoptFolder\u0028\u0029",
            "name": "adoptFolder",
            "summary": "Adopt\u0020a\u0020folderNode\u0020having\u0020source\u0020dimensions\u0020to\u0020target\u0020dimensions",
            "url": "classes/Neos-Folder-Domain-Service-FolderContext.html#method_adoptFolder"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service\\FolderContext\u003A\u003AdimensionString\u0028\u0029",
            "name": "dimensionString",
            "summary": "",
            "url": "classes/Neos-Folder-Domain-Service-FolderContext.html#method_dimensionString"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/neos-folder-domain-repository.html"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain",
            "name": "Domain",
            "summary": "",
            "url": "namespaces/neos-folder-domain.html"
        },                {
            "fqsen": "\\Neos\\Folder",
            "name": "Folder",
            "summary": "",
            "url": "namespaces/neos-folder.html"
        },                {
            "fqsen": "\\Neos",
            "name": "Neos",
            "summary": "",
            "url": "namespaces/neos.html"
        },                {
            "fqsen": "\\Neos\\Folder\\Domain\\Service",
            "name": "Service",
            "summary": "",
            "url": "namespaces/neos-folder-domain-service.html"
        }            ]
);
