Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              'Neos.Folder:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Neos\Folder\Controller\.*'
    mvc:
      routes:
        'Neos.Folder': true

  Folder:
    defaults:
      nodeType: 'Neos.Folder:Folder'
      titlePropertyKey: 'title'
      titlePathPropertyKey: 'titlePath'
      associationsPropertyKey: 'associations'
      # auto adopt on get request and no folder for requested dimension
      adoptOnEmpty: true
